name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
      - 'fix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 
      - 'ci'
      - 'refactor'
      - 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's New
  $CHANGES
  
  ## Contributors
  
  Thank you to our contributors for making this release possible:
  $CONTRIBUTORS
